import psycopg

# Connect to the database we created
connection = psycopg.connect(
    dbname="studentCourses",
    user="postgres",
    password="postgres",
    host="localhost"
)

# Open a cursor to perform database operations
with connection.cursor() as cur:

    # Execute our select all command
    cur.execute("""
                CREATE TABLE courses(
                id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name TEXT
                );
            """)
    cur.execute("""
               CREATE TABLE studentCourses(
               studentID int,
               courseID int
               );
            """)
    cur.execute("""
                INSERT INTO courses(id, name)
                VALUES (1,'SQL Server'), (2, 'ASP.NET MVC'), (3, 'MongoDB'), (4, 'Java'), (5, 'PHP');
            """)
    cur.execute("""
                INSERT INTO studentCourses(studentID, courseID)
                VALUES (1,1), (1,2), (1,3), (2,3), (2,4), (3,3), (3,5);
                """)
    
# Open a cursor to perform database operations
with connection.cursor() as cur:

    # Execute our Select all command
    cur.execute("""
                select * from courses;
                """)
    
    #print outputs
    print(cur.fetchall())

    cur.execute("""
                select * from studentCourses
                """)
    
    #print outouts
    print(cur.fetchall())